//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessUserInfo()
        {
            this.Business_Product = new HashSet<Business_Product>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public string EnterpriseName { get; set; }
        public string EnterpriseTaxNumber { get; set; }
        public string Email { get; set; }
        public string Head { get; set; }
        public string WeChatNumber { get; set; }
        public string PassWord { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> CollectionNum { get; set; }
        public int Shape { get; set; }
        public int Level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Business_Product> Business_Product { get; set; }
    }
}
