//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerUserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuyerUserInfo()
        {
            this.BuyerUser_Product = new HashSet<BuyerUser_Product>();
            this.User_Product = new HashSet<User_Product>();
            this.Tasks = new HashSet<Tasks>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Head { get; set; }
        public string WechatNumber { get; set; }
        public string PassWord { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<decimal> Get { get; set; }
        public int Shape { get; set; }
        public string EnterpriseName { get; set; }
        public string EnterpriseTaxNumber { get; set; }
        public int Level { get; set; }
        public Nullable<int> CollectionNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerUser_Product> BuyerUser_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Product> User_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
