//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerOrder
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Images { get; set; }
        public Nullable<int> order_steps { get; set; }
        public Nullable<int> Status { get; set; }
        public string Message { get; set; }
        public Nullable<int> Platform_order_status { get; set; }
        public string PlatformMessage { get; set; }
        public Nullable<int> Business_order_status { get; set; }
        public string BusinessMessage { get; set; }
        public Nullable<int> TasksID { get; set; }
        public string OrderCode { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<decimal> Commission { get; set; }
    }
}
