//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataDictionary
    {
        public int DictionaryID { get; set; }
        public int FDictionaryID { get; set; }
        public string Key { get; set; }
        public int Value { get; set; }
        public string Icon { get; set; }
        public string Color { get; set; }
        public string Custom { get; set; }
        public string Name { get; set; }
        public Nullable<int> int1 { get; set; }
        public Nullable<int> int2 { get; set; }
        public Nullable<int> int3 { get; set; }
        public string str4 { get; set; }
    
        public virtual FDataDictionary FDataDictionary { get; set; }
        public virtual FDataDictionary FDataDictionary1 { get; set; }
    }
}
