//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopEntities : DbContext
    {
        public ShopEntities()
            : base("name=ShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OrderPower> OrderPower { get; set; }
        public virtual DbSet<DataDictionary> DataDictionary { get; set; }
        public virtual DbSet<FDataDictionary> FDataDictionary { get; set; }
        public virtual DbSet<MoneyType> MoneyType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ClassiFication> ClassiFication { get; set; }
        public virtual DbSet<OperationMoney> OperationMoney { get; set; }
        public virtual DbSet<BuyerUser_Product> BuyerUser_Product { get; set; }
        public virtual DbSet<Business_Product> Business_Product { get; set; }
        public virtual DbSet<BusinessUserInfo> BusinessUserInfo { get; set; }
        public virtual DbSet<ProductComment> ProductComment { get; set; }
        public virtual DbSet<BuyerUserInfo> BuyerUserInfo { get; set; }
        public virtual DbSet<User_Product> User_Product { get; set; }
        public virtual DbSet<ReceiveOrder> ReceiveOrder { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<BuyerOrder> BuyerOrder { get; set; }
        public virtual DbSet<MoneyManager> MoneyManager { get; set; }
        public virtual DbSet<Product> Product { get; set; }
    }
}
