//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Product
    {
        public int ID { get; set; }
        public int ProuctID { get; set; }
        public int UserID { get; set; }
        public Nullable<bool> isCollected { get; set; }
        public Nullable<bool> isGood { get; set; }
        public Nullable<bool> IsReceiveOrder { get; set; }
    
        public virtual BuyerUserInfo BuyerUserInfo { get; set; }
        public virtual Product Product { get; set; }
    }
}
